<?php session_start();
  require_once('../../Funciones/Clases PDF/class.ezpdf.php');
  require("../../Clases/class.conexion.php");
  include("../../Clases/class.aula.php");
  $NuevoAul = new aula("","","","","");
  $NuevoAul->conec_BD();
  $NuevoAul->conectar_BD();
  $pdf =& new Cezpdf('LETTER','');
  $pdf->selectFont('../../Funciones/Clases PDF/fonts/Times-Roman.afm');
  $pdf->ezSetCmMargins('3','1','2','2');
  if($_GET[usu]!="")//si ya selecciono fecha y no es vacia
  {
    $NuevoAul->Buscar_aula($_GET[usu]);
	$array=$NuevoAul->Consultar();
	$id=$array->aul_id;
	$Nombre=$array->aul_nom;
			$accion='DESCARGAR';
		    $Operacion="DESCARGAR LA FICHA DEL AULA CON ID: ".$id." Y EL NOMBRE: ".$Nombre."";
		    $NuevoAul->guardar_accion($accion,"aulas",$Operacion);
    $Ti="FICHA DEL AULA";
    $datacreator = array ('Title'=>$Ti,'Author'=>$_SESSION[usuario],'Subject'=>'FICHA DEL AULA','Creator'=>'nusi243@hotmail.com','Producer'=>'Ing. Nuvia Sierra');
    $pdf->addInfo($datacreator);
    $pdf->ezStartPageNumbers(550,700,8,'right','',1);
    $pdf->addJpegFromFile('../../Imagenes/BanerGrande.jpg',5,715,600,70);
    $txttit= "\n\n\n\n\n<b>FICHA DEL AULA</b>\n\n\n";
    $pdf->ezText($txttit,14,array('justification'=>'center'));
    $optEnca = array('showLines'=>0, 'shaded'=>1, 'xOrientation'=>'center', 'width'=>400, 'fontSize'=>11, 'rowGap'=>2);
	$tituEncabezado = array('Columna1'=>'<b></b>', 'Columna2' =>'');
    $DaEncabezado[] = array_merge(array('Columna1'=>'<b>NUCLEO: </b>'),array('Columna2'=>''.$array->nuc_nom.''));
    $DaEncabezado[] = array_merge(array('Columna1'=>'<b>INFRAESTRUCTURA: </b>'),array('Columna2'=>''.$array->inf_nom.''));
    $DaEncabezado[] = array_merge(array('Columna1'=>'<b>NOMBRE: </b>'),array('Columna2'=>''.$Nombre.''));
    $DaEncabezado[] = array_merge(array('Columna1'=>'<b>UBICACIÓN: </b>'),array('Columna2'=>''.$array->aul_ubi.''));
	$pdf->ezTable($DaEncabezado, $tituEncabezado, '', $optEnca);
    $pdf->ezText("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", 14);
	$opt = array('showLines'=>0, 'shaded'=>0, 'xOrientation'=>'right', 'width'=>300, 'fontSize'=>7, 'rowGap'=>1);
	$tituEnca = array('Columna1'=>'<b></b>', 'Columna2' =>'');
    $DaEnca[] = array_merge(array('Columna1'=>'<b>IMPRESO POR: </b>'),array('Columna2'=>$_SESSION[usuario]));
	$dias=time();
    $HORA=date("H:i:s",$dias);
	$FECHA=date("d/m/Y",$dias);
    $DaEnca[] = array_merge(array('Columna1'=>'<b>FECHA DE IMPRESION: </b>'),array('Columna2'=>$FECHA));
    $DaEnca[] = array_merge(array('Columna1'=>'<b>HORA DE IMPRESION: </b>'),array('Columna2'=>$HORA));
	$pdf->ezTable($DaEnca, $tituEnca, '', $opt);
    $pdf->ezStream();
    header("Content-Disposition: attachment; filename=\"FICHA DEL AULA $Nombre.pdf\"");
  }?>